### ISSUE TITLE
Datasets Unavailable

### ISSUE THREAD

**Issue by Paeyus** [GuangchenW/BayesianOptimization#1]
The datasets used in the paper are not available in the repository for running the codes provided.

**Comment by GuangchenW** [comment]
Hi Paeyus,

The dataset used to be included in the arxiv of the related paper, but that seems to no longer be the case. I've committed the csv file to the repo, hope this helps.

**Comment by Paeyus** [comment]
Hello @GuangchenW ,

1. I would like to find out, if it is possible to evaluate the objective value based on the new experimental points generated before conducting the actual experiment to verify (in BoTorch)

2. And do you have an idea on how to deal with integer values?

**Comment by GuangchenW** [comment]
1. If what you mean is to compute the posterior of the points acquired, you can simply call the `posterior` function on point x (See [BoTorch doc](https://botorch.org/api/models.html#botorch.models.gp_regression.SingleTaskGP) on SingleTaskGP). This will give you the GP estimation of the output at x.

2. I've not done optimization over discrete space, but the `optimize_acqf_mixed` function seems to address your need. Check out [this](https://github.com/pytorch/botorch/issues/177#issuecomment-1351734575) issue on BoTorch GitHub. Alternatively, you can use the Ax interface to implement your own logic for integer parameters, though that may take some work.
If you are not constrained to BoTorch, you can also check out EmuKit, which allows you to specify whether a paramter is continuous or discrete.

**Comment by Paeyus** [comment]
Hello @GuangchenW, 
I checked out the document for 1. but I didn't see the code which points to that. Could you recheck and let me know? 
I tried using the full Gaussian process code from GPyTorch (Not SingleTaskGP), and used the prediction code in the documentation, but it seems to make a prediction value that is lower than the best observed point in my data

**Comment by GuangchenW** [comment]
Hi @Paeyus, `posterior` is a member method of the botorch Model base class, which `SingleTaskGP` inherents from. If you ctrl+F search for posterior, you should be able to find the api definition. 
I'm not so sure about your second question. I assume you are following [https://docs.gpytorch.ai/en/v1.6.0/examples/01_Exact_GPs/Simple_GP_Regression.html](https://docs.gpytorch.ai/en/v1.6.0/examples/01_Exact_GPs/Simple_GP_Regression.html)? If this is the case, you are using `ExactGP` with `GaussianLikelihood`, which assumes noisy data, meaning you are doing regression and the mean won't land exactly on the given observations (the picture at the bottom of the tutorial page shows this phenomenon).

Also be careful about running into the [XY Problem](https://xyproblem.info/)

**Comment by Paeyus** [comment]
Thank you very much, @GuangchenW. I am very grateful for your swift responses and assistance
